# Generated by Django 4.2 on 2025-10-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorista',
            fields=[
                ('codigo_interno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('titulo_profesional', models.CharField(choices=[('Bacteriólogo/a', 'Bacteriólogo/a'), ('Microbiólogo/a', 'Microbiólogo/a'), ('Biólogo/a', 'Biólogo/a')], max_length=50)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
    ]
