# Generated by Django 4.2 on 2025-10-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratoristaapi', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colesterol_total', models.FloatField()),
                ('colesterol_hdl', models.FloatField()),
                ('colesterol_ldl', models.FloatField()),
                ('trigliceridos', models.FloatField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('codigo_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='pacientes.paciente')),
                ('laboratorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='laboratoristaapi.laboratorista')),
            ],
        ),
    ]
